#!/bin/bash

echo -e "\n\nBrakeSqueal shell scripting \n\n"

python -V

var=$(python -c "import numpy; print numpy.__version__")
echo "Numpy $var"

var=$(python -c "import scipy; print scipy.__version__")
echo "Scipy $var"

var=$(python -c "import sphinx; print sphinx.__version__")
echo "Sphinx $var"

: <<'MYCOMMENT'
#To get a list of Python modules installed
python
import pip
installed_packages = pip.get_installed_distributions()
installed_packages_list = sorted(["%s==%s" % (i.key, i.version)
     for i in installed_packages])
print(installed_packages_list)
MYCOMMENT
